# Generated by Django 4.2.6 on 2023-10-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_rename_paleta_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='modelo',
            field=models.CharField(default='TuValorModeloPredeterminado', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=250),
        ),
    ]
