# Generated by Django 4.2.6 on 2023-11-01 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_producto_modelo_producto_tipo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Monitor',
        ),
    ]
