# Generated by Django 4.2.6 on 2023-11-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0003_video_delete_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=250)),
                ('anio', models.IntegerField()),
            ],
        ),
    ]
